### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nyalavarthi** [fugue/regula#27]
This framework seems like a great option for validating terraform and can be used as alternative to Sentinel, does this work on windows ? i am trying to set it up and run regula locally on windows with my simple terraform (aws) and not successful so far.  can you please provide windows installation instructions ? 

what difference between this example : 
./bin/regula ../my-tf-infra .: conveniently check ../my-tf-infr
and this example : 
opa eval -d /path/to/regula --input input.json 'data.fugue.regula.report'

**Comment by jaspervdj-luminal** [comment]
Hi @nyalavarthi, thanks for reporting this!  I spun up a Windows 10 machine on Azure to try this out.

1.  `/bin/regula ../my-tf-infra .: conveniently check ../my-tf-infr`

    This is a wrapper script that executes the commands you would do to run rego against terraform plans.  It is unlikely to work on Windows (except maybe through WSL) since it is a bash script.

2.  `opa eval -d /path/to/regula --input input.json 'data.fugue.regula.report'`

    This is the OPA command that the script actually executes, once the plan JSON has been generated.  This should work on Windows, since all tools involved are cross-platform.

I was able to do a test run of Regula on the Windows 10 machine by downloading [terraform], [OPA] and [regula-ci-example] (or you can use your own Terraform code instead of the example) and then running the following in PowerShell:

1.  Generate a JSON-based terraform plan:

    ```
    .\terraform.exe init .\regula-ci-example
    .\terraform.exe plan -refresh=false -out=infra .\regula-ci-example
    .\terraform.exe show -json infra >infra.json
    ```

2. Run OPA against this input file:

    ```
    .\opa_windows_amd64.exe eval -i .\infra.json -d .\regula\lib\ -d .\regula\rules\ 'data.fugue.regula.report'
    ```

Since these scripts are so short, we would be quite happy to include a PowerShell version of `/bin/regula`, but I'm not familiar enough with Windows to get that done -- if you would be interested in contributing there you would be more than welcome!

[terraform]: https://www.terraform.io/downloads.html
[OPA]: https://github.com/open-policy-agent/opa/releases
[regula-ci-example]: https://github.com/fugue/regula-ci-example

**Comment by nyalavarthi** [comment]
Thank you Jasper, it worked for me as well .
