### ISSUE TITLE
AWS IAM Password length policy failure

### ISSUE THREAD

**Issue by alleynec** [fugue/regula#55]
Hey I'm bumped regula libraries version up to version 0.4.0 and have some TF code that DOESN'T contain an IAM password policy and got a failure on the above rule. This rule is in the example/aws folder and worked in 0.3.0. Is there already fixed in the latest master commit? If so, I'll just use that.

"iam_password_length": {
  "resources": {
     "": {
        "id": "",
        "message": "No aws_iam_account_password_policy present",
        "type": "aws_iam_account_password_policy",
        "valid": false
      }
  },
  "valid": false
},

**Comment by jaspervdj-luminal** [comment]
Thanks for opening this ticket @alleynec!  This example is actually designed to fail when there's no password policy in the input, so it forces people to explicitly set it.  I suppose that's not what you would want all the time, but that's why it's in `examples/` and not `rules/`.  If you take out the first `policy` clause, the example should do what you want.

**Comment by alleynec** [comment]
That's interesting because it's never failed before and I've always included it in AWS deployments I've done. I see where it checks for an existing policy but I'm wondering why it never caught in previous checks.

**Comment by alleynec** [comment]
Hey Jasper, upon further review it looks like that rule is new compared to regula version 0.3.0. Closing this issue. Thank you.
