### ISSUE TITLE
howto debug a rule with fregot and regula input

### ISSUE THREAD

**Issue by ismailyenigul** [fugue/regula#68]
Hi,
I am trying to debug rules to print values that are processed after regula

https://github.com/fugue/regula/blob/master/examples/aws/ec2_t2_only.rego#L19
```
resource_type = "aws_instance"
 valid_instance_types[input.instance_type]
```
regula library eliminates most of the json parsing  part with standard rego codes
For example in above code you just specify `resource_type` and `input.instance_type` returns instance types

and in  https://github.com/fugue/regula/blob/master/rules/aws/ebs_volume_encrypted.rego#L35
encrypted attribute can be accessible directly with 
`input.encrypted == true`

How can I get regula processed `input` in fregot too? `input` in fregot displays all original input in json.

```

$ fregot repl lib rules tests examples/
F u g u e   R E G O   T o o l k i t
fregot v0.12.3 repl - use :help for usage info

repl% :break data.rules.ec2_t2_only.allow
Set breakpoint at rules.ec2_t2_only.allow

repl% data.rules.ec2_t2_only  with input as data.tests.rules.ec2_t2_only.mock_input
25|   valid_instance_types[input.instance_type]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rules.ec2_t2_only(debug)% 

rules.ec2_t2_only(debug)% input
= {
  "format_version": "0.1",
  "terraform_version": "0.12.18",
  "resource_changes": [
    {
      "change": {
        "actions": ["create"],
        "after_unknown": {
          "ami": true,
          "id": true,
          "associate_public_ip_address": true,
          "arn": true,
          "volume_tags": true,
          "network_interface": true,

```

I added 
```
rs[name] {
name := input.resource_changes
}
```
to  ec2_t2_only.rego
I can get some output with fregot ` data.rules.ec2_t2_only  with input as data.tests.rules.ec2_t2_only.mock_input` call.

```
},
  "rs": {[
    {
      "change": {
        "actions": ["create"],
        "after_unknown": {
          "ami": true,
          "id": true,
          "associate_public_
```

Also without using fregot,  how can I print/debug variables or a function call output in regula output.
`bash -x ./bin/regula ../ec2/ lib examples/aws/ec2_t2_only.rego` does not return anything about `rs` above.
I only got the rule final result.

**Comment by jaspervdj-luminal** [comment]
Right, these are good questions @ismailyenigul!  I realize we can use some more documentation, but for now I'll try to respond here and then later I can organize that into the README or a new tutorial.

# Input formats

Regula tries to do as much as possible before running the rule so the rule itself can be as easy to understand as possible.  However, this involves heavily mangling the input so I understand that it's sometimes not clear what is what.

There are 3 kinds of input "schemas" in Regula.  Different parts expect different kinds of input, which is the reason why something like this will not work:

```rego
data.rules.ec2_t2_only with input as data.tests.rules.ec2_t2_only.mock_input
```

Hopefully I can make clear why that is the case.  Here are the three "schemas" of input:

1.  There is the plan input.  This basically the straight-up output of `terraform plan` serialized to JSON.  You can recognize this by the following fields: `planned_values`, `resource_changes` and `configuration`.  It is useful to look at to see what information terraform gives you, but it probably shouldn't be touched directly since it's an internal format.

    The test cases have this format as `mock_plan_input`.  Regula takes this format and converts it to either (2) or (3).

2.  Is the input format used by advanced rules.  This mainly consists of a `resources: {...}` property.  All modules are flattened away and the resources are directly accessible.  However, it's not common to access them directly!  The `data.fugue` API provides something on top that provides the functions `fugue.resources(resource_type)`, `fugue.allow_resource(resource)` and `fugue.deny_resource(resource)` to deal with this.

    The test cases have this format as `mock_input`.  You can inspect this by doing something along the lines of:

    ```
    fregot repl .  # In the root of this repository
    repl% data.tests.rules.aws.inputs.cloudfront_distribution_https_infra.mock_input
    ```

    Wow, this prints a whole lot of stuff.  That's because the original plan is also included in this format, in case the rule may need it (though it's not great practice for a rule to rely on internals like that).  It's a bit cleaner to just look at the resources:

    ```
    fregot repl .  # In the root of this repository
    repl% data.tests.rules.aws.inputs.cloudfront_distribution_https_infra.mock_input.resources
    ```

    Because accessing `resources` is very common, you can also just use `mock_resources`:

    ```
    fregot repl .  # In the root of this repository
    repl% data.tests.rules.aws.inputs.cloudfront_distribution_https_infra.mock_resources
    ```

3.  Is the input used by simple rules (`allow`/`deny`) style.  This is just a single resource taken from (2).

    The test cases provide this in `mock_resources`; but this has all resources so to get what you want you'd pick a specific one, for example:

    ```
    data.tests.rules.aws.inputs.cloudfront_distribution_https_infra.mock_input.resources["aws_s3_bucket.bucket"]
    ```

This means that the correct invocation would be something like:

```
data.rules.ec2_t2_only with input as data.tests.examples.aws.inputs.ec2_t2_only_infra.mock_resources["aws_instance.valid_large"]
```

This is kind of long to type!  In order to avoid that problem, I usually have a `repl.rego` where I define common values, to make development easier.

# Printf-style debugging

`trace` in OPA logs a message to the decision log.  `fregot` works a little different and does not provide a decision log.  Instead, these messages go plainly to `stderr`, which can be very helpful for printf-style debugging!  If you write something akin to:

```rego
allow {
  trace("hello world")
  true
}
```

You should see the message `hello world` printed to the terminal when you evaluate `allow`.  One annoyance with this is that `fregot` may cache the allow value and avoid recomputing it; so you will not see the message when you evaluate `allow` again.  To avoid this, you can reload the code or restart the interpreter.

`trace(message)` takes a string, and it's often useful to print more complex values.  To do that, you can use `json.marshal` and/or `sprintf`.

```rego
allow {
  trace(json.marshal(input))`
  trace(sprintf("The whole input: %s", [json.marshal(input)]))`
}
```

# Step debugging

In order to do step debugging, we need to provide the right input to the right parts of Regula.  We can either do this automatically (which is arguably slower) or manually.

In order to do it automatically, we run Regula "as a whole", that way the right parts get provided in the right place by default.  This is what such a session would look like:

```
fregot repl .
repl% :break data.rules.ec2_t2_only.allow
repl% data.fugue.regula.report with input as data.tests.examples.aws.inputs.ec2_t2_only_infra.mock_plan_input
19|   valid_instance_types[input.instance_type]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rules.ec2_t2_only(debug)%
```

The way this works is that `report` will eventually (after converting the input) evaluate the rule, at which point the breakpoint will trigger.

An alternative is to call `allow` directly.  In that case we need to provide the right resource:

```
repl% :break data.rules.ec2_t2_only.allow
Set breakpoint at rules.ec2_t2_only.allow
repl% data.rules.ec2_t2_only.allow with input as  data.tests.examples.aws.inputs.ec2_t2_only_infra.mock_resources["aws_instance.valid_large"]
19|   valid_instance_types[input.instance_type]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rules.ec2_t2_only(debug)%
```

Always providing the resource can get extremely tedious, even if you have it saved as a variable in `repl.rego`.  What you can also do is save the json given by `data.tests.examples.aws.inputs.ec2_t2_only_infra.mock_resources["aws_instance.valid_large"]` to `input.json`.  You can then invoke `fregot` with this input file directly:

```
fregot repl --input input.json .
repl% :break data.rules.ec2_t2_only.allow
Set breakpoint at rules.ec2_t2_only.allow
repl% data.rules.ec2_t2_only.allow  # automatically uses the right input!
```

I hope this answered most of your questions.  Let me know if there's something else I can help with!

**Comment by ismailyenigul** [comment]
Thanks for the detailed explanation.   Likely, I will be using trace. I could not see any explanation about trace in fregot README :) It might be good to update there as well in addition to updates in regula repo.
Thanks again. I will do some debugging and keep you updated

**Comment by ismailyenigul** [comment]
```
# Regula expects advanced rules to contain a `policy` rule that holds a set
# of _judgements_.
policy[p] {
  resource = ebs_volumes[_]
  is_encrypted(resource)
  p = fugue.allow_resource(resource)
} {
  resource = ebs_volumes[_]
  not is_encrypted(resource)
  p = fugue.deny_resource(resource)
}
```
It might be good to explain the logic above. Is the above `policy`  AND or OR ? It seems it is OR logic

**Comment by curtis-fugue** [comment]
That policy is written as an incremental definition. The OPA documentation has a [helpful section on this](https://www.openpolicyagent.org/docs/latest/policy-language/#incremental-definitions).

Because one definition has `is_encrypted(resource)` and the other has `not is_encrypted(resource)` then we know that only one of those can be true at a time. So in that way the logic is an `OR` as you described.
